language: ruby
rvm:
  - 2.4.5
cache: bundler
before_install:
  - gem update --system
  - gem install bundler
before_script:
  - chmod +x ./bin/cibuild
script: "./bin/cibuild"
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: agilefloripa
  on:
    repo: mingomax/afconf