language: ruby
rvm:
  - 2.4.5
cache:
  - bundler
before_script:
  - chmod +x ./bin/cibuild
script: "./bin/cibuild"
deploy:
  provider: heroku
  api_key:
    secure: qrY3KCjOEgtmrg5uKvD6tGqegRCSC/oDJTGeaYuTbfXG2v+CWRc1R5Q+g6+wIAcVks/f6r0KL7778caUqXaIC8/RJbjWuOEewKVPJx5mx8uFkqRT8kOq/0ToxlZapOMI3rHo2EfS0YycBdDxrEcO6Jdu0gMpwVBiU7vhIbFQrFZj7rMG2mtjSRNexCYdtDesO3RgVtGVyTjRDy8h4UPovopTg7yiA3w+jcNUJkZLqQN8uEGggFTtRVG8/ajYldZIfw5RiqulgijYpz2/WfP3SMWAyrK3OHqWE2FIvxgBPc8+PQ0GCX9N/CTMo9XpkWaQO6lk1QS+MH09Txr9qsNc/78ZqYxZ/oB0GTWPoHUFod/MC6dSpL5Od8J7Fl7tWGOlEo0Sw31drsxYGduokxtDyLzuHYRQANNMPmcxEgyxAPUJVD8fbRmfnaRvKJnt1mbEgOkk5KlMwFCWXJW+z7mHhYZJgkIMVF7UTSHNrW0qNzYtCeipgfbSXA4g2XTvCTjh4WrI0XHFrp/zeUGiGvKlIgh3KBSoZwF5I8ct9u8QtOFk4KEL4TVRJyamJ2BNVQtomF1n3UvUbOe5KiNwrO1EEc3ga/yHFNzyuAreHQk2A8KK0nUJA/tgtNlrvUhcejo91Qu2P8Eht5D0kPeRJYDJpnDXYeLWUh76IJDyKzKXJWQ=
  app: agilefloripa
  on:
    repo: mingomax/afconf