title: Agile Floripa
description: > # this means to ignore newlines until "baseurl:"
  Estamos indo para a edição 2019 do Agile Floripa! Uma onda de cooperação ágil que vem crescendo em Florianópolis. Este evento veio como meio de fortalecer a comunidade manezinha e catarinense e proporcionar espaço para que as grandes atividades e inovações realizadas no nosso estado sejam compartilhadas de maneira transparente e horizontal!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.agilefloripa.com.br" # the base hostname & protocol for your site
lang: "pt_BR"
# Build settings
markdown: kramdown

facebook:
  app_id:

logo: "../2019_pages/images/agilefloripa-logo.png"

social:
  name: Agile Floripa
  link: "https://www.facebook.com/agilefloripa"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2019_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/agilefloripa
  - title: twitter
    url: https://twitter.com/agilefloripa
  - title: instagram
    url: https://instagram.com/agilefloripa

# Build settings
markdown: kramdown
permalink: pretty
exclude:
  - vendor
